# Generated by Django 4.2.27 on 2026-01-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='current_session_type',
            field=models.CharField(blank=True, choices=[('WEB', 'Web'), ('REMOTE', 'Remote')], help_text='Current session type (WEB/REMOTE)', max_length=20, null=True),
        ),
    ]
