# Generated by Django 4.2.27 on 2026-01-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendance_current_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='daily_sessions_count',
            field=models.IntegerField(default=0, help_text='Number of sessions completed today'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='max_daily_sessions',
            field=models.IntegerField(default=5, help_text='Maximum allowed sessions per day'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_working_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total working hours for the day', max_digits=5),
        ),
    ]
