# Generated by Django 4.2.27 on 2026-01-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_missing_attendance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_working_hours',
            field=models.FloatField(default=0.0, help_text='Total hours worked today across all sessions'),
        ),
    ]
