# Generated by Django 4.2.27 on 2026-01-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_el_co_fields'),
        ('employees', '0004_alter_locationlog_options_locationlog_accuracy_and_more'),
    ]

    operations = [
    ]
